"""staff grievances and team management

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 13:30:25.314891
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_grievances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.String(length=50), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('accused_user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_investigator_id', sa.Integer(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('resolution_action', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accused_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_investigator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_grievances_accused_user_id'), 'staff_grievances', ['accused_user_id'], unique=False)
    op.create_index(
        op.f('ix_staff_grievances_assigned_investigator_id'),
        'staff_grievances',
        ['assigned_investigator_id'],
        unique=False,
    )
    op.create_index(op.f('ix_staff_grievances_created_at'), 'staff_grievances', ['created_at'], unique=False)
    op.create_index(op.f('ix_staff_grievances_id'), 'staff_grievances', ['id'], unique=False)
    op.create_index(op.f('ix_staff_grievances_reporter_id'), 'staff_grievances', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_staff_grievances_status'), 'staff_grievances', ['status'], unique=False)
    op.create_index(op.f('ix_staff_grievances_tracking_id'), 'staff_grievances', ['tracking_id'], unique=True)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_permission')
    )
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_table('staff_grievance_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('storage_name', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['staff_grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_name')
    )
    op.create_index(
        op.f('ix_staff_grievance_attachments_grievance_id'),
        'staff_grievance_attachments',
        ['grievance_id'],
        unique=False,
    )
    op.create_index(op.f('ix_staff_grievance_attachments_id'), 'staff_grievance_attachments', ['id'], unique=False)
    op.create_table('staff_grievance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_confidential_note', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grievance_id'], ['staff_grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_grievance_events_created_at'), 'staff_grievance_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_staff_grievance_events_event_type'), 'staff_grievance_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_staff_grievance_events_grievance_id'), 'staff_grievance_events', ['grievance_id'], unique=False)
    op.add_column('users', sa.Column('primary_department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('primary_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_primary_location', 'users', 'locations', ['primary_location_id'], ['id'])
    op.create_foreign_key('fk_users_primary_department', 'users', 'departments', ['primary_department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_primary_department', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_primary_location', 'users', type_='foreignkey')
    op.drop_column('users', 'primary_location_id')
    op.drop_column('users', 'primary_department_id')
    op.drop_index(op.f('ix_staff_grievance_events_grievance_id'), table_name='staff_grievance_events')
    op.drop_index(op.f('ix_staff_grievance_events_event_type'), table_name='staff_grievance_events')
    op.drop_index(op.f('ix_staff_grievance_events_created_at'), table_name='staff_grievance_events')
    op.drop_table('staff_grievance_events')
    op.drop_index(op.f('ix_staff_grievance_attachments_id'), table_name='staff_grievance_attachments')
    op.drop_index(op.f('ix_staff_grievance_attachments_grievance_id'), table_name='staff_grievance_attachments')
    op.drop_table('staff_grievance_attachments')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_staff_grievances_tracking_id'), table_name='staff_grievances')
    op.drop_index(op.f('ix_staff_grievances_status'), table_name='staff_grievances')
    op.drop_index(op.f('ix_staff_grievances_reporter_id'), table_name='staff_grievances')
    op.drop_index(op.f('ix_staff_grievances_id'), table_name='staff_grievances')
    op.drop_index(op.f('ix_staff_grievances_created_at'), table_name='staff_grievances')
    op.drop_index(op.f('ix_staff_grievances_assigned_investigator_id'), table_name='staff_grievances')
    op.drop_index(op.f('ix_staff_grievances_accused_user_id'), table_name='staff_grievances')
    op.drop_table('staff_grievances')
    # ### end Alembic commands ###
