"""add aadhar and pan

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-07 17:44:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None

from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('end_users')]
    if 'aadhar' not in columns:
        op.add_column('end_users', sa.Column('aadhar', sa.String(length=20), nullable=True))
    if 'pan_card' not in columns:
        op.add_column('end_users', sa.Column('pan_card', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_users', 'pan_card')
    op.drop_column('end_users', 'aadhar')
    # ### end Alembic commands ###
